version: 3

projects:
  - name: network
    dir: network
    workflow: custom
    autoplan:
      when_modified: ["*.tf", "*.tfvars"]
      enabled: true

workflows:
  custom:
    plan:
      steps:
        - run: terraform plan -var-file=vars_dev.tfvars
    apply:
      steps:
        - run: terraform apply -var-file=vars_dev.tfvars

