version: 3
projects:
  - name: azure-network
    dir: network
    workspace: default
    terraform_version: v1.3.0
    autoplan:
      when_modified: ["*.tf", "*.tfvars"]
      enabled: true
    apply_requirements: []
    workflow: custom

workflows:
  custom:
    plan:
      steps:
        - init
        - plan:
            extra_args: ["-var-file=vars_dev.tfvars"]
    apply:
      steps:
        - apply

