version: 3
projects:
  - name: network
    dir: network
    workflow: myworkflow
    terraform_version: v1.3.0
    autoplan:
      enabled: true
      when_modified: ["*.tf", "*.tfvars"]

workflows:
  myworkflow:
    plan:
      steps:
        - run:
            command: terraform init -input=false
            output: hide
        - run: terraform plan -input=false -var-file=vars_dev.tfvars -out $PLANFILE
    apply:
      steps:
        - run: terraform apply $PLANFILE

