# terraform.yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: network-tf
  namespace: terraform-system
spec:
  interval: 5m
  approvePlan: auto
  path: ./network
  sourceRef:
    kind: GitRepository
    name: terraform-repo
  vars:
    - name: vnet_name
      value: "vnet1"
    - name: resource_group_name
      value: "rg112"
    - name: resource_group_location
      value: "japaneast"
    - name: address_space
      value: "10.0.0.0/16"
    - name: subnet_names
      value: "[\"web\", \"app\", \"db\"]"
    - name: subnet_prefixes
      value: "[\"10.0.1.0/24\", \"10.0.2.0/24\", \"10.0.3.0/24\"]"
    - name: tags
      value: |
        {
          environment = "development"
        }
  runnerPodTemplate:
    spec:
      containers:
        - name: main
          image: ghcr.io/weaveworks/tf-runner:v0.16.0

